// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAio0vOC6WBIq3SMKwar7EdM0u9JmTbNro',
    appId: '1:104485251385:web:a37d9cf621d875fd08a0e8',
    messagingSenderId: '104485251385',
    projectId: 'iti2023training-bffab',
    authDomain: 'iti2023training-bffab.firebaseapp.com',
    storageBucket: 'iti2023training-bffab.appspot.com',
    measurementId: 'G-7HM14MVYDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABvf8Xzy5JbNk-Uu0fuNEOuHzHP_Fdd1g',
    appId: '1:104485251385:android:9c9465660ac64c6908a0e8',
    messagingSenderId: '104485251385',
    projectId: 'iti2023training-bffab',
    storageBucket: 'iti2023training-bffab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArljInO48z-Hg-6bZVK7hyNiEuVx6Owkc',
    appId: '1:104485251385:ios:4c7624950a6fba3c08a0e8',
    messagingSenderId: '104485251385',
    projectId: 'iti2023training-bffab',
    storageBucket: 'iti2023training-bffab.appspot.com',
    iosClientId: '104485251385-sn5123aqjdk54n72ip0dvp0tg4hppnbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArljInO48z-Hg-6bZVK7hyNiEuVx6Owkc',
    appId: '1:104485251385:ios:26c46df603e5e09508a0e8',
    messagingSenderId: '104485251385',
    projectId: 'iti2023training-bffab',
    storageBucket: 'iti2023training-bffab.appspot.com',
    iosClientId: '104485251385-ln0tvj8blrfplljbjdebcsc05m9ps6f8.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
